// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { CompanyCode } from 'services/API_COMPANYCODE_SRV';

@Injectable()
export class ODataService {
  constructor(private readonly httpService: HttpService) {}

  async getEntities(): Promise<CompanyCode[]> {
    const url = 'https://api.sap.com/api/API_COMPANYCODE_SRV';
    const response = await firstValueFrom(this.httpService.get(url));
    console.log(response.data);
    return response.data.value; // OData responses typically have a 'value' array
  }
}
